### ISSUE TITLE
Note: this case does not support the rev 2 pcb

### ISSUE THREAD

**Issue by woenlee** [jakehappersett/Prime_E_AngleMod#1]
This case only supports rev1 pcb. Rev2 is not compatible. (which is totally fine/understandable) but it would be useful to be stated in the README

**Comment by jakehappersett** [comment]
"Back in my day...." 

Thanks so much for the input, I didn't even realize there was a rev2 out!  When I had originally designed this there were two Prime_E boards: one that did not have the top angled portion cut out (I guess rev0?) and then the one I designed it for which I now know was rev1 

I'll go ahead and update the README but I'd like to modify the case design to be compatible with rev2 at some point.  I've experimented with quite a few different mounting patterns etc since this has been designed so I'll bet I can make a simpler assembly that still looks the same. 
❤️

**Comment by woenlee** [comment]
Hi jake, sorry I closed the issue, it was a dumb mistake on my part! I had
scaled the case to be printed in ABS but I had scaled it a bit too much.
The case indeed does fit!

However, the 2 holes on the top and bottom of the middle of the plate are
now irrelevant. That’s the only change I think! Thank you for the case!
